spring:
  datasource:
    username: root
    password: Ventana1204
    url: jdbc:mysql://localhost:3306/control_stock
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  imageProduct: imageProduct/

base:
    url: "http://localhost:8080"